title: Code Guide
description: For people who tend to forget command lines and need cheat sheets. Look no further!
base: /code-guide/
head:
  -
    - link
    - rel: shortcut icon
      type: image/x-icon
      href: ./favicon.ico
themeConfig:
  nav:
    - text: COMMANDS
      link: /commands/
    - text: UI
      link: /ui/
  sidebar:
    - title: Commands
      children:
        - /commands/
        - /commands/vue
        - /commands/mongoDB
        - /commands/git
        - /commands/heroku
    - title: UI
      children:
        - /ui/
